buildpack:
  name: Blazar-Buildpack-Java

enabled: true

provides:
  - name: easy-random-bean-validation
    version: 5.0.1-$GIT_BRANCH-SNAPSHOT

depends:
  - easy-random-core
  - easy-random-randomizers

env:
  SET_VERSION_OVERRIDE: 5.0.1-$GIT_BRANCH-SNAPSHOT

